### ISSUE TITLE
wget vlang.io/v.c is a security hole

### ISSUE THREAD

**Issue by whoizit** [ndac-todoroki/asdf-v#1]
you should not use make, cause wget vlang.io/v.c is security hole. Server can be compromised any time. Instead you should use v.c repo https://github.com/vlang/vc.git and build it without make

```
    cc -std=gnu11 -w -o vc v.c 
    ./vc -o v . 

    # recompile itself
    ./v -o v . 
```

look into my ArchLinux PKGBUILD https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vlang-git

**Comment by whoizit** [comment]
https://github.com/vlang/v/pull/522#issuecomment-505145371

**Comment by whoizit** [comment]
https://github.com/vlang/v/releases/tag/v0.1.0

**Comment by ndac-todoroki** [comment]
@whoizit Thanks for the information! I'll look on this later today.

**Comment by ndac-todoroki** [comment]
Removed usage of make in #2 ! I also removed the special `master` reference, since v0.1.0 seems to have all the code sources in the tar.gz. (Now the CI will succeed)
Thanks again!
